"""Mention « contenu genere par IA » — AI Act, article 50.

GL-19 (DEC-0817-03 / TASK-0823-01). L'obligation court depuis le 02/08/2026.
Le site vitrine est conforme depuis le 15/09 ; l'application ne l'etait pas.

Une seule source de verite pour le texte, parce que la mention doit etre
identique sur les quatre sorties client (SDS Word, SDS HTML, autres livrables
Word, et les fenetres de dialogue du Studio cote frontend, qui reprennent le
meme libelle dans `frontend/src/lib/aiDisclosure.ts`).

Deux emplacements par livrable, et non un seul :

  - le **corps** du document, visible a la lecture ;
  - les **metadonnees** du fichier (`core_properties` pour Word,
    `<meta name="generator">` pour le HTML), qui survivent au copier-coller
    d'un extrait alors que le pied de page, lui, se perd.
"""
from __future__ import annotations

from typing import Optional

# Le texte, et rien d'autre, est la donnee de reference. « Genere par la
# plateforme » ne satisfait pas l'article 50 : la mention doit nommer
# l'intelligence artificielle.
MENTION_IA = {
    "fr": (
        "Contenu genere par une intelligence artificielle. "
        "A relire et valider par un professionnel avant tout usage."
    ),
    "en": (
        "Content generated by artificial intelligence. "
        "To be reviewed and validated by a professional before any use."
    ),
}

CATEGORIE_DOCX = {
    "fr": "Contenu genere par IA",
    "en": "AI-generated content",
}

LANGUE_PAR_DEFAUT = "fr"


def _normaliser(langue: Optional[str]) -> str:
    """Regle 6 : une langue inconnue ne fait pas disparaitre la mention.

    Elle retombe sur le francais — la langue de reference des livrables — et
    jamais sur une chaine vide, qui reviendrait a retirer silencieusement une
    mention legalement obligatoire.
    """
    if not isinstance(langue, str):
        return LANGUE_PAR_DEFAUT
    code = langue.strip().lower()[:2]
    return code if code in MENTION_IA else LANGUE_PAR_DEFAUT


def mention_ia(langue: Optional[str] = LANGUE_PAR_DEFAUT) -> str:
    """La mention, dans la langue demandee."""
    return MENTION_IA[_normaliser(langue)]


def categorie_ia(langue: Optional[str] = LANGUE_PAR_DEFAUT) -> str:
    """Le libelle de categorie ecrit dans les metadonnees du fichier."""
    return CATEGORIE_DOCX[_normaliser(langue)]


def appliquer_mention_docx(document, langue: Optional[str] = LANGUE_PAR_DEFAUT) -> None:
    """Ajoute la mention au corps et aux metadonnees d'un document python-docx.

    Idempotent : appelee deux fois sur le meme document, elle n'empile pas
    deux mentions (le generateur de gabarit sauvegarde parfois plusieurs fois).
    """
    texte = mention_ia(langue)

    deja_presente = any(texte in paragraphe.text for paragraphe in document.paragraphs)
    if not deja_presente:
        paragraphe = document.add_paragraph()
        execution = paragraphe.add_run(texte)
        execution.italic = True
        execution.font.size = _taille_mention()

    proprietes = document.core_properties
    proprietes.comments = texte
    proprietes.category = categorie_ia(langue)

    return None


def _taille_mention():
    from docx.shared import Pt

    return Pt(8)


def sauvegarder_docx_avec_mention(
    document,
    chemin: str,
    langue: Optional[str] = LANGUE_PAR_DEFAUT,
):
    """Point de sortie unique des generateurs Word : mention puis sauvegarde.

    Passer par cette fonction plutot que par `document.save(...)` est ce qui
    garantit qu'aucun livrable Word ne sort sans sa mention.
    """
    appliquer_mention_docx(document, langue=langue)
    document.save(chemin)
    return chemin
