"""
WBS Schema - INC-01
Pydantic schema for Work Breakdown Structure generated by Marcus (Architect)

This schema validates and documents the structure of WBS deliverables.
"""
from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Any
from datetime import date
from enum import Enum


class TaskStatus(str, Enum):
    """Status of a WBS task"""
    NOT_STARTED = "not_started"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    BLOCKED = "blocked"


class RiskSeverity(str, Enum):
    """Risk severity levels"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class AgentType(str, Enum):
    """Available agents for task assignment"""
    MARCUS = "Marcus"      # Architect
    DIEGO = "Diego"        # Apex Developer
    ZARA = "Zara"          # LWC Developer
    RAJ = "Raj"            # Admin/Config
    ELENA = "Elena"        # QA
    JORDAN = "Jordan"      # DevOps
    LUCAS = "Lucas"        # Trainer
    AISHA = "Aisha"        # Data


# ============== Task Models ==============

class WBSTask(BaseModel):
    """Individual task within a WBS phase"""
    id: str = Field(..., description="Unique task identifier (e.g., TASK-001)")
    name: str = Field(..., description="Task name/title")
    description: Optional[str] = Field(None, description="Detailed task description")
    assigned_agent: Optional[AgentType] = Field(None, description="Agent assigned to this task")
    effort_days: float = Field(..., ge=0.5, description="Estimated effort in days")
    dependencies: List[str] = Field(default_factory=list, description="List of task IDs this depends on")
    deliverables: List[str] = Field(default_factory=list, description="Expected deliverables from this task")
    gap_refs: List[str] = Field(default_factory=list, description="References to gap analysis IDs")
    status: TaskStatus = Field(default=TaskStatus.NOT_STARTED, description="Current task status")
    
    # Optional enriched fields
    acceptance_criteria: Optional[List[str]] = Field(None, description="Criteria for task completion")
    technical_notes: Optional[str] = Field(None, description="Technical implementation notes")
    salesforce_components: Optional[List[str]] = Field(None, description="SF components involved")
    
    class Config:
        use_enum_values = True


# ============== Phase Models ==============

class WBSPhase(BaseModel):
    """A phase within the WBS containing multiple tasks"""
    id: str = Field(..., description="Phase identifier (e.g., PHASE-1)")
    name: str = Field(..., description="Phase name")
    duration_weeks: float = Field(..., ge=0.5, description="Duration in weeks")
    start_week: int = Field(..., ge=1, description="Starting week number")
    end_week: int = Field(..., ge=1, description="Ending week number")
    objectives: List[str] = Field(default_factory=list, description="Phase objectives")
    tasks: List[WBSTask] = Field(default_factory=list, description="Tasks in this phase")
    
    class Config:
        use_enum_values = True


# ============== Milestone Models ==============

class WBSMilestone(BaseModel):
    """Project milestone with criteria"""
    id: str = Field(..., description="Milestone identifier")
    name: str = Field(..., description="Milestone name")
    target_week: int = Field(..., ge=1, description="Target week for milestone")
    phase: str = Field(..., description="Associated phase")
    criteria: List[str] = Field(default_factory=list, description="Acceptance criteria")


# ============== Risk Models ==============

class WBSRisk(BaseModel):
    """Project risk with mitigation strategy - flexible schema"""
    model_config = {"extra": "allow"}
    
    id: str = Field(..., description="Risk identifier")
    risk: str = Field(..., description="Risk title")
    description: str = Field(..., description="Detailed description")
    severity: str = Field(..., description="Risk severity (case-insensitive)")
    probability: str = Field(..., description="Probability (low/medium/high)")
    impact: str = Field(..., description="Impact description")
    # Mitigation can be string or list
    mitigation: Any = Field(..., description="Mitigation strategy (string or list)")
    owner: Optional[str] = Field(None, description="Risk owner")
    
    @property
    def severity_normalized(self) -> str:
        """Get normalized severity"""
        return self.severity.lower() if self.severity else "medium"
    
    @property
    def mitigation_list(self) -> List[str]:
        """Get mitigations as list"""
        if isinstance(self.mitigation, list):
            return self.mitigation
        return [self.mitigation] if self.mitigation else []


# ============== Resource Allocation ==============

class ResourceAllocation(BaseModel):
    """Resource allocation for an agent - accepts multiple field formats"""
    model_config = {"extra": "allow"}  # Allow extra fields
    
    role: str = Field(..., description="Agent role description")
    total_days: Optional[float] = Field(None, ge=0, description="Total allocated days")
    total_effort_days: Optional[float] = Field(None, ge=0, description="Total effort days (alternative)")
    allocation_percentage: Optional[int] = Field(None, description="Percentage allocation")
    tasks: List[str] = Field(default_factory=list, description="Assigned task IDs")
    focus_areas: Optional[List[str]] = Field(None, description="Focus areas")
    peak_week: Optional[int] = Field(None, description="Week with highest workload")
    
    @property
    def effort_days(self) -> float:
        """Get effort days from either field"""
        return self.total_effort_days or self.total_days or 0


class ResourceAllocationOLD(BaseModel):
    """Resource allocation for an agent"""
    role: str = Field(..., description="Agent role description")
    total_days: float = Field(..., ge=0, description="Total allocated days")
    tasks: List[str] = Field(default_factory=list, description="Assigned task IDs")
    peak_week: Optional[int] = Field(None, description="Week with highest workload")


# ============== Dependencies ==============

class DependencyInfo(BaseModel):
    """External or internal dependency - flexible schema"""
    model_config = {"extra": "allow"}
    
    # Accept either id or dependency as identifier
    id: Optional[str] = Field(None, description="Dependency ID")
    dependency: Optional[str] = Field(None, description="Dependency name")
    description: str = Field(..., description="Description")
    owner: Optional[str] = Field(None, description="Owner")
    required_by: Optional[str] = Field(None, description="Task requiring this")
    status: Optional[str] = Field(None, description="Status")
    due_date: Optional[str] = Field(None, description="Due date")
    
    @property
    def identifier(self) -> str:
        """Get the identifier from either field"""
        return self.id or self.dependency or "unknown"


class WBSDependencies(BaseModel):
    """Project dependencies"""
    model_config = {"extra": "allow"}
    external: List[DependencyInfo] = Field(default_factory=list)
    internal: List[DependencyInfo] = Field(default_factory=list)


# ============== Main WBS Schema ==============

class WBSContent(BaseModel):
    """
    Complete Work Breakdown Structure schema.
    
    This is the deliverable generated by Marcus (Architect) after analyzing
    the Solution Design Specification from Olivia (BA).
    """
    # Metadata
    artifact_id: str = Field(..., description="Unique artifact identifier")
    title: str = Field(..., description="WBS document title")
    project_name: str = Field(..., description="Project name")
    created_date: str = Field(..., description="Creation date (ISO format)")
    created_by: str = Field(default="Marcus", description="Creator agent")
    
    # Timeline
    total_duration_weeks: int = Field(..., ge=1, description="Total project duration in weeks")
    total_effort_days: int = Field(..., ge=1, description="Total effort in days")
    
    # Core structure
    phases: List[WBSPhase] = Field(..., min_length=1, description="Project phases")
    milestones: List[WBSMilestone] = Field(default_factory=list, description="Key milestones")
    
    # Resource planning
    resource_allocation: Dict[str, ResourceAllocation] = Field(
        default_factory=dict, 
        description="Resource allocation by agent"
    )
    
    # Project management
    critical_path: List[str] = Field(default_factory=list, description="Critical path task IDs")
    risks_and_mitigations: List[WBSRisk] = Field(default_factory=list, description="Risk register")
    dependencies: Optional[WBSDependencies] = Field(None, description="Project dependencies")
    
    # Additional info
    assumptions: List[str] = Field(default_factory=list, description="Project assumptions")
    success_criteria: List[str] = Field(default_factory=list, description="Success criteria")
    notes: List[str] = Field(default_factory=list, description="Additional notes")
    
    class Config:
        use_enum_values = True
        
    def get_all_tasks(self) -> List[WBSTask]:
        """Get all tasks from all phases"""
        tasks = []
        for phase in self.phases:
            tasks.extend(phase.tasks)
        return tasks
    
    def get_tasks_by_agent(self, agent: AgentType) -> List[WBSTask]:
        """Get tasks assigned to a specific agent"""
        return [t for t in self.get_all_tasks() if t.assigned_agent == agent]
    
    def get_task_by_id(self, task_id: str) -> Optional[WBSTask]:
        """Get a specific task by ID"""
        for task in self.get_all_tasks():
            if task.id == task_id:
                return task
        return None
    
    def validate_dependencies(self) -> List[str]:
        """Validate that all task dependencies exist"""
        all_task_ids = {t.id for t in self.get_all_tasks()}
        errors = []
        for task in self.get_all_tasks():
            for dep in task.dependencies:
                if dep not in all_task_ids:
                    errors.append(f"Task {task.id} has invalid dependency: {dep}")
        return errors


# ============== Wrapper Schema ==============

class WBSDeliverable(BaseModel):
    """
    Wrapper for WBS deliverable as stored in agent_deliverables table.
    """
    agent_id: str = Field(default="architect")
    deliverable_type: str = Field(default="architect_wbs")
    success: bool = Field(default=True)
    content: WBSContent = Field(..., description="WBS content")
    metadata: Optional[Dict[str, Any]] = Field(None)


# ============== Example WBS ==============

def get_example_wbs() -> dict:
    """Return an example WBS for documentation/testing"""
    return {
        "artifact_id": "WBS-2025-001",
        "title": "Work Breakdown Structure - Example Project",
        "project_name": "Salesforce CRM Implementation",
        "created_date": "2025-12-08",
        "created_by": "Marcus",
        "total_duration_weeks": 12,
        "total_effort_days": 120,
        "phases": [
            {
                "id": "PHASE-1",
                "name": "Discovery & Setup",
                "duration_weeks": 2,
                "start_week": 1,
                "end_week": 2,
                "objectives": ["Environment setup", "Requirements finalization"],
                "tasks": [
                    {
                        "id": "TASK-001",
                        "name": "Setup Development Sandbox",
                        "description": "Configure dev sandbox with required features",
                        "assigned_agent": "Jordan",
                        "effort_days": 1,
                        "dependencies": [],
                        "deliverables": ["Configured sandbox", "Access credentials"]
                    }
                ]
            }
        ],
        "milestones": [
            {
                "id": "M1",
                "name": "Environment Ready",
                "target_week": 2,
                "phase": "PHASE-1",
                "criteria": ["All sandboxes configured", "Team access granted"]
            }
        ],
        "resource_allocation": {
            "Jordan": {
                "role": "DevOps Engineer",
                "total_days": 10,
                "tasks": ["TASK-001"],
                "peak_week": 1
            }
        },
        "critical_path": ["TASK-001"],
        "risks_and_mitigations": [
            {
                "id": "R1",
                "risk": "Sandbox Limits",
                "description": "May hit sandbox limits during development",
                "severity": "medium",
                "probability": "medium",
                "impact": "Development delays",
                "mitigation": "Request additional sandboxes early",
                "owner": "Jordan"
            }
        ],
        "assumptions": ["Client provides timely feedback"],
        "success_criteria": ["All tests passing", "UAT sign-off"],
        "notes": ["Weekly status meetings scheduled"]
    }
