/**
 * Mentions IA — AI Act, article 50. GL-19 (DEC-0817-03 / TASK-0823-01).
 *
 * Obligation en vigueur depuis le 02/08/2026. Deux mentions distinctes, parce
 * que l'article en demande deux choses differentes :
 *
 *   - `AI_CHAT_DISCLOSURE` — « vous echangez avec une IA », au premier contact,
 *     dans chaque fenetre de dialogue du Studio ;
 *   - `AI_DELIVERABLE_DISCLOSURE` — « contenu genere par IA », en pied de
 *     livrable. Le meme texte que `backend/app/utils/ai_disclosure.py`, pour
 *     qu'un SDS lu dans le Studio et le meme SDS telecharge en Word ne se
 *     contredisent pas.
 *
 * Module pur, sans dependance, teste par `frontend/tests/aiDisclosure.test.ts`.
 */

export type DisclosureLang = 'en' | 'fr';

export const AI_CHAT_DISCLOSURE: Record<DisclosureLang, string> = {
  fr: 'Vous échangez avec une intelligence artificielle, pas avec une personne.',
  en: 'You are talking to an artificial intelligence, not to a person.',
};

/**
 * Doit rester identique a `MENTION_IA` dans
 * `backend/app/utils/ai_disclosure.py` (sans accents cote backend, qui ecrit
 * dans des metadonnees de fichier).
 */
export const AI_DELIVERABLE_DISCLOSURE: Record<DisclosureLang, string> = {
  fr: 'Contenu généré par une intelligence artificielle. À relire et valider par un professionnel avant tout usage.',
  en: 'Content generated by artificial intelligence. To be reviewed and validated by a professional before any use.',
};

const LANG_PAR_DEFAUT: DisclosureLang = 'fr';

/**
 * Ramene n'importe quelle valeur a une langue connue.
 *
 * Regle 6 : une langue inattendue retombe sur le francais, jamais sur une
 * chaine vide — sinon un code de langue inconnu ferait disparaitre une mention
 * legalement obligatoire, sans que rien ne le signale.
 */
function normaliser(langue: unknown): DisclosureLang {
  if (typeof langue !== 'string') return LANG_PAR_DEFAUT;
  const code = langue.trim().toLowerCase().slice(0, 2);
  return code === 'en' || code === 'fr' ? code : LANG_PAR_DEFAUT;
}

/** « Vous échangez avec une IA » — bandeau d'une fenetre de dialogue. */
export function aiChatDisclosure(langue: unknown = LANG_PAR_DEFAUT): string {
  return AI_CHAT_DISCLOSURE[normaliser(langue)];
}

/** « Contenu généré par IA » — pied d'un livrable affiche dans le Studio. */
export function aiDeliverableDisclosure(langue: unknown = LANG_PAR_DEFAUT): string {
  return AI_DELIVERABLE_DISCLOSURE[normaliser(langue)];
}
